export const routesConstant = {
  HOME: "/",
  CREDIT_CARDS: "/credit-cards",
  CREDIT_CARD_COMPARISON: "/credit-card-comparison-details",
  BLOGS: "/blogs",
  FAQ: "/faq",
  PRESS_RELEASE: "/press-release",
  SUCCESS_STORIES: "/success-stories",
  PERSONAL_LOAN: "/personal-loan",
  CREDIT_SCORE_REPORT: "/credit-score-report",
  CREDIT_CARD_QUESTIONAIRRE: "/credit-card-questionnaire",
  PERSONAL_LOAN_QUESTIONAIRRE: "/personal-loan-questionairre",
  PERSONAL_LOAN_QUESTIONAIRRE_APPLICATION:
    "/personal-loan-questionairre-application",
  LOANS: "#",
  RESOURCES: "#",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_CONDITION: "/terms-and-conditions",
  RECOMMENDED_CREDIT_CARD: "/recommended-credit-card",
  RECOMMENDED_PERSONAL_LOAN: "/recommended-personal-loan",
  CREDIT_CARD_APPLICATION_FORM: "/credit-card-application-form",
};
