import { Col, Container, Row } from "react-bootstrap";
import styles from "./style.module.scss";
import { PageTitle, Text } from "@styles/styledComponent";
import { address, email, phone, whiteKashti } from "@public/assets";
import { ContactForm, CustomImage } from "@components";
import Link from "next/link";
import { routesConstant } from "@utils/routesConstant";
import { ChevronRight } from "react-bootstrap-icons";

const Page = () => {
  return (
    <main className={styles.termsPage}>
      {/* Get in Touch */}
      <section className={styles.headerSection}>
        <Container style={{ backgroundImage: `url(${whiteKashti.src})` }}>
          <Row>
            <Col lg={12}>
              <Text className={styles.breadCrumbs}>
                <span>Resources</span>
                <ChevronRight />
                <span>Terms & Conditions</span>
              </Text>
            </Col>
          </Row>
          <Row>
            <Col lg={12}>
              <PageTitle>Terms & Conditions</PageTitle>
              <Text>Last Updated - 29th May, 2024</Text>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Content */}
      <section className={styles.contentSection}>
        <Container>
          <Row>
            <Col xs={12} md={3} lg={3}>
              <Link href={routesConstant.PRIVACY_POLICY}>Privacy Policy</Link>
              <Link
                href={routesConstant.TERMS_CONDITION}
                className={styles.activePage}
              >
                Terms and Conditions
              </Link>
            </Col>
            <Col xs={12} md={9} lg={9}> 
              <div className={styles.contentBox}>
                <Text>KASHTI FINSERV PRIVATE LIMITED, whose registered office is situated at JP Nagar 3rd phase Banaglore , 560078India (hereinafter shall be referred to as "Kashti" or "Company" or "us" or "we" are the owner of the mobile application by the name Kashti ("App") and website at www.kashti.com("Website") (App and Website are hereinafter together referred to as the "Platform").</Text>
                <Text>As a user ("User" or "You") of the Platform, You understand that the Platform provides access between multiple Users in the form of consumers, financial institutions, data partners and other partners lenders, borrowers, service providers etc. with a view to facilitate lending and borrowing activities, including providing other financial products credit cards etc. between the Users. A list of our lending partners is provided in Schedule 1 herewith.</Text>
                <Text>It is hereby clarified that the term "Users" shall mean any person using the Platform i.e. consumers, financial institutions, regulated entities, and other partners. Your use of this Platform implies that You have read, understood and agreed to abide by the following, disclaimer, terms & conditions ("Terms & Conditions").</Text>
                <Text>These Terms & Conditions together with our privacy policy govern Your usage of the Platform and the terms for the purchase of the Products from the Platform ("Product").</Text>
                <Text>Please read these Terms & Conditions carefully before accessing or using our Platform. By accessing or using any part of the Platform, you agree to be bound by these Terms & Conditions. If You do not agree to all the terms and conditions of this agreement, then You may not access the Platform or use any services provided by Us.</Text>
                <Text>GENERAL Kashti is a platform facilitating loan transactions between borrowers and the NBFCs/Banks. All loan applications are approved and sanctioned by NBFCs/Banks registered with RBI and communicated upfront during Loan application.</Text>
                <Text>The Platform provides access to an online platform bringing together consumers, financial institutions, data partners and other partners willing to abide by the Terms & Conditions herein. Kashti's lending partners provide various kinds of personal loan products as specifically supplied by the Users through the Platform. In the event You wish to avail any of the Products displayed on the Platform, you will be required to provide certain information and our representatives may contact You through phone or email to understand Your requirements. Kashti provides various services, including but not limited to ("Services"):</Text>
                <Text>Facilitating the purchase and sale of Products on its Platform; Assisting its Users to obtain a Product from various banks and non-banking financial companies who are the lending partners of Kashti; Assisting its Users to obtain their credit reports through authorized agents partnered with Kashti. Kashti will monitor and update the credit report obtained by the customer through the use of the Platform as and when Kashti receives such report from the authorized agents; Provision of data analysis and social score based on device data and the User's Facebook, Twitter, LinkedIn or any other social media accounts that are linked with User's account on the Platform. In the event You have registered Your phone number on the 'Do Not Disturb' registers with Your network provider,</Text>
                <Text>You shall ensure to take all steps to enable the Company's representative's to contact You via phone to provide details about different financial products and You shall ensure that such calls received by You are pursuant to You providing Us with information and You shall not register a complaint with the relevant authorities for the same.</Text>
                <Text>For the provision of the above mentioned Services, Kashti will be using and sharing the information of the User with multiple financial institutions and other parties, as may be required for the purpose mentioned above and Kashti shall also run multiple credit checks to be able to get the best available offers to suit the needs of the Users.</Text>
                <Text>The collection, storing, use and transfer of information shared by the User shall be governed in accordance with the Privacy Policy is available at https://www.Kashti.in/privacy-policy.</Text>
                <Text>ELIGIBILITY The User of this Platform unequivocally declares and agrees that the User is a natural/ legal person who has attained the age of at least 21 years and is legally allowed to enter into a contract in India. The User is allowed to utilize the Services in accordance with the terms and conditions detailed hereinafter. By registering on the Platform, the User hereby undertakes to agree and abide by the Terms & Conditions detailed herein. If the User violates any of these Terms & Conditions or otherwise violates an agreement entered into through the medium of the Platform, Kashti may terminate the User's membership, delete his/her profile and any content or information posted online by the User on the Platform and/or prohibit the User from using or accessing the Platform at any time in its sole discretion, with or without notice, including without limitation if Kashti believes that User is under the age of 21 years.</Text>
                <Text>ACCEPTANCE OF TERMS AND CONDITIONS As a User of this Platform, you have agreed to the Terms & Conditions provided hereunder or anywhere else on this Platform including but not limited to disclaimers on this Platform. You are advised to read and understand the said Terms & Conditions and in case You do not wish to agree to these Terms & Conditions, please refrain from using the Platform.</Text>
                <Text>Kashti reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms and Conditions, at any time. Any changes made to these Terms and Conditions will be communicated to the email address of the User maintained in our records, within a reasonable time from the date of modification. Kashti does not take responsibility in case the email address provided by the User is either incorrect or does not belong to the user. The User's continued use of the Platform following the notification of modification of these Terms and Conditions will be construed to mean the acceptance by the User of the modified Terms and Conditions.</Text>
                <Text>YOUR ACCOUNT If You wish to use the Platform, You are required to maintain an account and will be required to furnish certain information and details, including Your name, email ID, contact number and any other information deemed necessary by Kashti and as further detailed in the Privacy Policy. You are responsible for maintaining the confidentiality and security of Your account, password, and activities that occur in or through Your account and for restricting access to Your computer to prevent unauthorized access to Your account. You agree to accept responsibility for all activities that occur under Your account or password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if You have any reason to believe that Your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner. Please ensure that the details You provide Us with are true, correct, accurate and complete.</Text>
                <Text>Upon Kashti gaining knowledge or having any reasonable suspicion that the information provided by You is wrong, inaccurate or incorrect, Kashti shall immediately terminate Your account without any notice to You in this regard. In the event of any changes to the information shared by You at the time of registering Yourself on the Platform, You shall be responsible for forthwith notifying the said changes to Us.</Text>
                <Text>You can access and update most of the information You provided us on the 'dashboard' area of Your account after You log in or by writing to Us at Support@Kashti.com. The right to use this Platform is personal to the User and is not transferable to any other person or entity.</Text>
                <Text>You shall at all times abide by the Terms and Conditions stated herein and any breach of these conditions may also lead to Kashti terminating Your

 account and appropriate civil and criminal remedies will be sought against You as provided under the laws of India.</Text>
                <Text>PRIVACY Kashti collects certain information from You in order to provide the Services. Kashti's use of Your personal information is governed in accordance with the Privacy Policy.</Text>
                <Text>LICENSE AND ACCESS Kashti grants You a limited license to access and use the Platform for availing the Services, but not to download any material from it (other than page caching) or modify it, or any portion of it, except with express written consent of Kashti and/or its affiliates, as may be applicable. Any unauthorized access to the Platform or any networks, servers or computer systems connected to the Platform and any attempt to modify, adapt, translate or reverse engineer any part of the Platform or re-format or frame any portion of the pages of the Platform, save to the extent expressly permitted by these Terms & Conditions, is not permitted.</Text>
                <Text>This license is non-transferable and does not permit any resale or commercial use of this Platform or its contents; any downloading or copying of account information for the benefit of anyone other than Your use; or any use of data mining, robots, or similar data gathering and extraction tools. The Platform or any portion of the Platform (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without the express written consent of Kashti and/or its affiliates, as may be applicable. Any unauthorized use of the Platform shall terminate the permission or revoke the license granted by Kashti.</Text>
                <Text>You are permitted to use content delivered to You through the Service only on the Service. You may not copy, reproduce, distribute, or create derivative works from this content. Further, You agree not to reverse engineer or reverse compile any of the Service technology, including but not limited to, any Java applets associated with the Service.</Text>
                <Text>MONITORING OF THE PLATFORM AND YOUR ACCOUNT Kashti has the right and liberty to monitor the content of the Platform at all times which shall include information provided in Your account. The monitoring of the Platform/Platform is important to determine the veracity of the information provided by You and that every User remains in consonance with the Terms & Conditions provided herein.</Text>
                <Text>Subject to the Terms & Conditions mentioned herein, Kashti shall also have the liberty to remove any objectionable content that is in contravention of the Terms & Conditions herein or share such information with any governmental authority as per procedures laid down by the law for the time being in force in India.</Text>
                <Text>SERVICE SUSPENSION Kashti may stop providing the Services and may terminate use of it at any time without giving notice of termination to You. Unless Kashti informs the User otherwise, upon any termination, (a) the rights and licenses granted to You in these terms will end; and (b) User must stop using the Platform forthwith. Kashti reserves the right to suspend or cease providing any Service and shall have no liability or responsibility to the User in any manner whatsoever if it chooses to do so.</Text>
                <Text>PROHIBITED USES In addition to other prohibitions as set forth in the Terms & Conditions, You are prohibited from using the Platform: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (9) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate Your use of the Service or any related website for violating any of the prohibited uses.</Text>
                <Text>REFUND & CANCELLATION POLICY Any additional payment made by You shall be refunded back within 30 days pursuant to the reconciliation of the accounts by Kashti. There will be no cancellation of the service once You have received the loan amount in Your bank account.</Text>
                <Text>LIMITATION OF LIABILITY AND DISCLAIMER OF WARRANTIES Notwithstanding anything to the contrary contained herein, neither Kashti nor its affiliated companies, subsidiaries, officers, directors, employees or any related party shall have any liability to You or to any third party for any indirect, incidental, special or consequential damages or any loss of revenue or profits arising under or relating to these Terms & Conditions. To the maximum extent permitted by law, You waive, release, discharge and hold harmless Kashti, its affiliated and subsidiary companies, and each of their directors, officers, employees, and agents, from any and all claims, losses, damages, liabilities, expenses and causes of action arising out of Your use of the Platform. As a User, You also acknowledge that Kashti has maintained and carried out all possible checks and balances to assure the credibility of the Users as listed on the Platform. The information provided on the Platform is based on the information that is provided to Kashti. In case the User does not disclose any information to Kashti, and the same is not found out at the first instance by Kashti despite all measures adopted to certify the ratings or credibility of a User, Kashti shall not be responsible for any claims or liabilities. Kashti in any event is not responsible for any default in return of money that is borrowed from the lender and the lender shall have the exclusive right to initiate proceedings against the defaulter borrower. Kashti shall to the best of its abilities aid the concerned User in terms of the provision of information to initiate any legal proceedings. However, Kashti shall not be responsible for any default on behalf of the User. Kashti is an information platform and the User is entitled to conduct its own diligence before taking any steps to initiate the processes outlined in the Website.</Text>
                <Text>Kashti does not make any representations or warranties on behalf of the financial service providers, banks or NBFCs partnered with Kashti with respect to the financial products/loans provided by such partners on the Platform.</Text>
                <Text>Kashti shall be responsible only to the extent of providing the Services and all liabilities and obligations of the customers/User with respect to the financial products provided by the partners shall be governed by the separate agreement executed between such financial partners and the customers and Kashti shall have no liability in this regard whatsoever.</Text>
                <Text>YOUR USE OF THE SERVICE AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. COMPANY EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND AS TO THE SERVICE AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THAT OF THIRD PARTIES) INCLUDED IN OR ACCESSIBLE FROM THE SERVICE, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. COMPANY MAKE NO WARRANTY THAT: (i) THE SERVICE WILL MEET YOUR REQUIREMENTS, (1) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, OR (V) ANY ERRORS IN THE TECHNOLOGY WILL BE CORRECTED AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE COMPANY OR SERVICE PROVIDER THROUGH OR FROM THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS.</Text>
                <Text>YOU FURTHER AGREE THAT NEITHER THE COMPANY OR THIRD PARTY SERVICE PROVIDER NOR ANY OF THEIR AFFILIATES, ACCOUNT PROVIDERS OR ANY OF THEIR AFFILIATES WILL BE LIABLE FOR ANY HARMS, WHICH LAWYERS AND COURTS OFTEN CALL DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, EVEN IF COMPANY OR SERVICE PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE SERVICE/PLATFORM; (ii) THE COST OF GETTING SUBSTITUTE GOODS AND SERVICES, (1) ANY PRODUCTS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO, THROUGH OR FROM THE SERVICE; (IV) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (v) STATEMENTS OR CONDUCT OF ANYONE ON THE SERVICE; EVEN IF THE PROVIDER HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES

; OR (Vii) ANY OTHER MATTER RELATING TO THE SERVICE. THE MAXIMUM LIABILITY OF Kashti SHALL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU TO THE COMPANY FOR THE SERVICE.</Text>
                <Text>INDEMNITY You agree to indemnify, save, and hold Kashti, its affiliates, contractors, employees, officers, directors, agents and its third party associates, licensors, and partners harmless from any and all claims, demands, losses, damages, and liabilities, costs and expenses, including without limitation legal fees and expenses, arising out of or related to Your use or misuse of the Services or of the Website or App or Platform, any violation by You of these Terms & Conditions, or any breach of the representations, warranties, and covenants made by You herein or Your infringement of any intellectual property or other right of any person or entity, or as a result of any threatening, libellous, obscene, harassing or offensive material posted/transmitted by You on the Platform. Kashti reserves the right, at Your expense, to assume the exclusive defence and control of any matter for which You are required to indemnify Kashti, including rights to settle, and You agree to cooperate with Kashtis' defence and settlement of these claims. Kashti will use reasonable efforts to notify You of any claim, action, or proceeding brought by a third party that is subject to the foregoing indemnification upon becoming aware of it. This paragraph shall survive termination of this Terms & Conditions.</Text>
                <Text>E-VOUCHER Your use of the E-Voucher shall be subject to the terms of use of the issuer of the E-Voucher. Your use of the E-Voucher shall be at your sole risk and Kashti is not responsible for the E-voucher once issued. Kashti is not responsible for the end use of the E-voucher. The products are purchased by You directly from the merchant/vendor. You understand and agree that Kashti is not responsible for the delivery or the quality or performance of the same.</Text>
                <Text>you understand that the final product delivery would be subject to the stock and terms and conditions of the partner shopping platform. You further understand that You shall have no resource to Kashti for the items purchased by You using the E-Voucher. You are solely responsible for the safety and security of the E-Voucher and your account. You understand that E-Voucher cannot be redeemed for Cash or Credit. Orders placed using E-Voucher (s) cannot be cancelled at a later point in time. You understand that the E-Voucher will expire after 12 months from the date of issue and any corresponding unused balance shall be forfeited thereafter. The validity of E-Vouchers cannot be extended, new E-Vouchers cannot be provided against the expired/unused E-Vouchers.</Text>
                <Text>ADVERTISERS/THIRD PARTY LINKS ON THE PLATFORM Kashti accepts no responsibility for advertisements contained within the Platform. Kashti has no control over and accepts no responsibility for the content of any website or mobile application to which a link from the Platform exists. Such linked websites and mobile applications are provided "as is" for User's convenience only with no warranty, express or implied, for the information provided within them. Kashti does not provide any endorsement or recommendation of any third party website or mobile application to which the Platform provides a link. Further, the Users consent and agree that the content provided in the Website and the App shall be synced and shall be available in both mediums.</Text>
                <Text>USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS If, at Kashti's request, You send certain specific submissions (for example contest entries) or without a request from Us, You send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), You agree that We may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that You forward to Us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments.</Text>
                <Text>You agree that Your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that Your comments will not contain libellous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than Yourself, or otherwise mislead Us or third-parties as to the origin of any comments. You are solely responsible for any comments You make and their accuracy. We take no responsibility and assume no liability for any comments posted by You or any third-party.</Text>
                <Text>You are licensing to the Company and its service providers, any information, data, passwords, materials or other content (collectively, "Content") You provide through or to the Service. Company and service provider of Company may use, modify, display, distribute and create new material using such Content to provide the Service to You. Company and Service Provider may also use, sell, license, reproduce, distribute and disclose aggregate, non-personally identifiable information that is derived through Your use of the Service. By submitting Content, You automatically agree, or promise that the owner of such Content has expressly agreed that, without any particular time limit, and without the payment of any fees, Company and its third party service provider may use the Content for the purposes set out above. As between Company and third party service provider, Company owns Your confidential account information.</Text>
                <Text>ACKNOWLEDGEMENTS You acknowledge that Kashti is a platform bringing Users together and that the Kashti is not engaged in either granting loan or borrowing any money or assistance for any financial products from any member using the Kashti Platform. You acknowledge that the use of the financial products is entirely based on the negotiations between the Users and third party and neither Kashti nor its affiliates, contractors, employees, officers, directors, agents and their third party associates, licensors and partners have any interest with regard to any financial products assistance procured by or to a registered User. You acknowledge that Kashti will not be responsible for any claim or damage in case of use of the financial products.</Text>
                <Text>Kashti in no manner warrants or guarantees the performance of a third party service provider that is providing services through the App. You acknowledge that Kashti in no manner guarantees that the Users have provided all the information on this App which is true and correct including his address, phone numbers etc. You acknowledge that it is Your responsibility to verify the information about the person on the Platform and Kashti is in no manner liable if the information provided on this App is untrue or incorrect. You acknowledge that Kashti is in no manner responsible for any claim of money or damages in the event one person fails to either grant loan or a person fails to repay the loan or misrepresents his financial status or commits a fraud or cheating or any other such illegal act.</Text>
                <Text>APPLICABLE LAWS Your use of this Platform and any Terms & Conditions stated in this agreement is subject to the laws of India. In case of any disputes arising out of the use of the Website, the Courts of Bangalore will have exclusive jurisdiction.</Text>

                {/* Added Content from the Document */}
                <div className={styles.sectionTitle}>CONSENT ABOUT ACCESS TO CREDIT INFORMATION THROUGH EXPERIAN</div>
                <p>
                  This End User Agreement (the “Agreement”) is made between you (the “User” or “You”) and Kashti legally known as Kashti Finserv Pvt Ltd. a private limited company having its registered office at “ICS SQUARE” BUILDING NO.57 GROUND FLOOR 8TH MAIN ROAD 3RD PHASE J.P NAGAR NEAR SBI BANK Bangalore- 560078 (“CLIENT” “Us” or “We” which term shall include its successors and permitted assigns). The User and CLIENT shall be collectively referred to as the “Parties”
                </p>
                <p>
                  You hereby consent to Kashti being appointed as your authorised representative to receive your Credit Information on an ongoing basis for up to a period of 6 months from Experian to pull the Bureau Score to push the lead to the lending partner associated with the Kashti (“End Use Purpose”).
                </p>
                <p>
                  BY EXECUTING THIS AGREEMENT / CONSENT FORM YOU ARE EXPRESSLY AGREEING TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE AGGREGATE SCORES INFERENCES REFERENCES AND DETAILS (AS DEFINED BELOW)(TOGETHER REFERRED AS “CREDIT INFORMATION”). YOU HEREBY ALSO IRREVOCABLY AND UNCONDITIONALLY CONSENT TO SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO YOU AND KASHTI BY USING EXPERIAN TOOLS ALGORITHMS AND DEVICES AND YOU HEREBY AGREE ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.
                </p>
                
                <p>
                  <strong>Information Collection Use Confidentiality No-Disclosure And Data Purging</strong><br />
                  KASHTI shall access your Credit Information as your authorized representative and KASHTI shall use the Credit Information for limited End Use Purposes consisting of and in relation to the services proposed to be availed by you from KASHTI. We shall not aggregate retain store copy reproduce republish upload post transmit sell or rent the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed herein and in furtherance to CICRA.
                </p>
                <

p>
                  The Parties agree to protect and keep confidential the Credit Information both online and offline. The Credit Information shared by you or received by us on your behalf shall be destroyed purged and erased promptly within 1 (one) Business Day upon the completion of the transaction/ End Use Purpose for which the Credit Information report was procured for up to a maximum of 6 months.
                </p>
                <p>
                  If you want to change your consent criteria to either withdraw (reject) or enrol (accept) at a later date you will need to make a request directly to support@kashti.com. This request may take several days to come in to effect once the request has been made.
                </p>
                <div className={styles.subSectionTitle}>Governing Law And Jurisdiction</div>
                <p>
                  The relationship between you and KASHTI shall be governed by laws of India and all claims or disputes arising there from shall be subject to the exclusive jurisdiction of the courts of Mumbai.
                </p>
                <div className={styles.subSectionTitle}>Definitions:</div>
                <p>
                  Capitalised terms used herein but not defined above shall have the following meanings:<br />
                  <strong>“Business Day”</strong> means a day (other than a public holiday) on which banks are open for general business in Mumbai.<br />
                  <strong>“Credit Information Report”</strong> means the credit information/scores/aggregates/variables/inferences or reports that shall be generated by Experian.<br />
                  <strong>“Credit Score”</strong> means the score which shall be mentioned on the Credit Information Report which shall be computed by Experian.<br />
                  <strong>“CICRA”</strong> shall mean the Credit Information Companies (Regulation) Act 2005 read with the Credit Information Companies Rules 2006 and the Credit Information Companies Regulations 2006 and shall include any other rules and regulations prescribed thereunder.
                </p>
                <p>
                  PLEASE READ THE ABOVE MENTIONED TERMS AND CONDITIONS AND CLICK ON “ACCEPT” FOLLOWED BY THE LINK BELOW TO COMPLETE THE AUTHORISATION PROCESS/ FOR SHARING OF YOUR CREDIT INFORMATION BY EXPERIAN WITH KASHTI IN ITS CAPACITY AS YOUR AUTHORISED REPRESENTATIVE. BY CLICKING “ACCEPT” YOU AGREE AND ACCEPT THE DISCLAIMERS AND TERMS AND CONDITIONS SET OUT HEREIN.
                </p>
                <p>
                  ** This document is an electronic record in terms of the Information Technology Act 2000 and Rules made there under and the amended provisions pertaining to electronic records.
                </p>

                {/* Original "Grievances" Section */}
                <Text>GRIEVANCES Users have complete authority to file a complaint/share feedback if they are disappointed by services rendered by Kashti. They can give their complaint/feedback in writing or by way of an email to the following: Email:support@Kashti.com</Text>
              </div>
            </Col>
          </Row>
        </Container>
      </section>
    </main>
  );
};

export default Page;